export type Project = {
  slug: string;
  title: string;
  category: string;
  desc: string;
  tech: string[];
  color: string;
  metric: string;
  image: string;
  objectPosition?: string;
  // 'cover' (default) fills and may crop; 'contain' shows the whole image (for infographic-style thumbnails).
  imageFit?: 'cover' | 'contain';
  // CSS aspect-ratio for the card thumbnail (e.g. '1200 / 896'). Used with imageFit 'contain'
  // so the card slot matches the image and fills edge to edge with no cropping or empty bars.
  imageAspect?: string;
  year: string;
  challenge: string;
  solution: string;
  result: string;
  features: string[];
  gallery: string[];
  video?: string | string[];
  // How the project was delivered. 'upwork'/'direct' = built for a paying client,
  // 'internal' = built in-house by the team as a showcase product.
  clientType?: 'upwork' | 'direct' | 'internal';
  // Only ever populated with genuine, verifiable client feedback.
  testimonial?: {
    quote: string;
    author: string;
    rating: number;
    source?: string;
  };
};

export const projects: Project[] = [
  {
    slug: 'nutra-ai-health-coach',
    title: 'A.I Health Coach',
    category: 'AI/ML',
    desc: 'NutraAI Health Coach is an AI-powered wellness assistant designed to help users achieve their fitness and health goals through personalized guidance and smart recommendations. The platform provides customized nutrition plans, workout suggestions, daily activity tracking, and habit-building support based on each user’s lifestyle and objectives. Powered by intelligent AI interactions, NutraAI acts as a virtual health coach that keeps users motivated, consistent, and focused on improving their overall well-being through data-driven insights and real-time support.',
    tech: ['RAG', 'AI', 'React', 'TypeScript', 'Node.js'],
    color: '#10b981',
    metric: 'Personalized wellness tracking',
    image: '/Nutra_AI/Thumbnail.png',
    year: '2026',
    challenge: 'Maintaining a healthy lifestyle with personalized nutrition and fitness plans is difficult without an expensive human coach.',
    solution: 'NutraAI delivers a tailored experience using AI to generate customized workout and nutrition plans.',
    result: 'Users stay motivated and achieve health goals using an accessible, data-driven AI virtual coach.',
    features: [
      'Customized nutrition plans',
      'Personalized workout suggestions',
      'Daily activity tracking',
      'Habit-building support',
      'Intelligent virtual coach interactions'
    ],
    gallery: [
      '/Nutra_AI/Interface.png',
      '/Nutra_AI/interface2.png',
      '/Nutra_AI/interface3.png',
      '/Nutra_AI/Thumbnail.png'
    ],
    video: '/Nutra_AI/NutraAI_Video.mp4',
  },
  {
    slug: 'traffic-detection-yolo',
    title: 'Traffic Detection using YOLO',
    category: 'AI/ML',
    desc: 'Developed and deployed an AI-powered Traffic Monitoring System using YOLO for real-time vehicle detection, tracking, and traffic analysis. The system detects cars, buses, trucks, motorcycles, and pedestrians from CCTV/video feeds with high accuracy. Features include vehicle counting, congestion monitoring, and traffic flow analysis. Built using Python, YOLO, OpenCV, and Deep Learning techniques for smart surveillance and intelligent transportation solutions. We deployed it on Railway and built the web interface using next js and html/css',
    tech: ['Computer Vision', 'Python', 'YOLO', 'OpenCV', 'Next.js', 'Deep Learning'],
    color: '#eab308',
    metric: 'Real-time vehicle detection',
    image: '/Traffic_Detection_YOLO/Thumbnail.png',
    year: '2026',
    challenge: 'Monitoring traffic congestion and vehicle flow manually through CCTV is inefficient and error-prone.',
    solution: 'An AI-powered monitoring system using YOLO and OpenCV that processes video feeds in real-time, accurately detecting and classifying various vehicles.',
    result: 'Provides actionable insights into traffic flow and congestion, fully deployed on Railway with a sleek Next.js dashboard.',
    features: [
      'Real-time vehicle detection (cars, buses, trucks, motorcycles, pedestrians)',
      'Vehicle tracking and counting',
      'Congestion monitoring',
      'Traffic flow analysis',
      'Web interface deployed on Railway'
    ],
    gallery: [
      '/Traffic_Detection_YOLO/Interface1.png',
      '/Traffic_Detection_YOLO/interface2.png',
      '/Traffic_Detection_YOLO/interface3.png',
      '/Traffic_Detection_YOLO/interface4.png',
      '/Traffic_Detection_YOLO/interface5.png',
      '/Traffic_Detection_YOLO/interface6.png'
    ],
    video: '/Traffic_Detection_YOLO/Yolo Traffic Detection Demo.mp4',
  },
  {
    slug: 'optipro-retinal-disease-detection',
    title: 'OptiPro: Retinal Disease Detection',
    category: 'AI/ML',
    desc: 'End-to-end AI-powered retinal disease detection platform for clinical support. Classifies retinal scans into CNV, DME, Drusen, and Normal using ResNet-101 with Grad-CAM heatmap visualization for explainable AI output. Includes a full doctor panel, patient portal, appointment workflows, and AI-generated PDF medical reports.',
    tech: ['Computer Vision', 'PyTorch', 'ResNet-101', 'Flask', 'React', 'Supabase', 'PostgreSQL', 'Grad-CAM', 'Gemini API'],
    color: '#00e5ff',
    metric: '4 disease classes detected',
    image: '/portfolio/optipro.png',
    year: 'Aug 2025',
    challenge: 'Ophthalmologists face growing patient volumes and retinal disease diagnosis requires specialized expertise. Manual analysis of OCT scans is time-consuming and prone to human error, particularly in under-resourced clinics.',
    solution: 'We developed OptiPro, a clinical-grade AI platform that classifies retinal scans into CNV, DME, Drusen, and Normal using a fine-tuned ResNet-101 model. Grad-CAM heatmaps provide explainable AI output so clinicians can verify the model\'s reasoning. The platform includes a doctor panel, patient portal, appointment workflows, and AI-generated PDF medical reports.',
    result: 'OptiPro accurately classifies four retinal disease categories with explainable heatmap visualizations, enabling faster clinical workflows and AI-assisted diagnostics that support ophthalmologists rather than replacing their judgment.',
    features: [
      'ResNet-101 classification of 4 retinal disease types',
      'Grad-CAM heatmap visualization for explainability',
      'Full doctor panel with patient management',
      'Patient portal with appointment booking',
      'AI-generated PDF medical reports via Gemini API',
      'Supabase-backed real-time data layer',
    ],
    gallery: [
      '/Opti_Pro/thumbnail.png',
      '/Opti_Pro/screenshot-1.png',
      '/Opti_Pro/screenshot-2.png',
      '/Opti_Pro/screenshot-3.png',
      '/Opti_Pro/screenshot-4.png',
    ],
    video: '/Opti_Pro/demo.mp4',
  },
  {
    slug: 'ai-student-stress-management',
    title: 'AI Student Stress Management',
    category: 'AI/ML',
    desc: 'AI-based platform that detects and helps reduce student stress, anxiety, and depression using machine learning. Analyzes questionnaire data for early mental health detection, delivers personalized recommendations like breathing exercises and relaxation techniques, and includes an AI chatbot for real-time emotional support.',
    tech: ['NLP', 'Predictive Analytics', 'Python', 'Machine Learning', 'React', 'PostgreSQL', 'AI Chatbot', 'REST API'],
    color: '#f472b6',
    metric: 'Early stress detection',
    image: '/studentstressmanagement.png',
    year: 'Feb 2025',
    challenge: 'University students often struggle with undetected stress, anxiety, and depression. Traditional counseling cannot scale to reach every student, and many avoid seeking help due to stigma.',
    solution: 'We built an AI-powered platform that uses machine learning to analyze questionnaire responses and detect early signs of mental health issues. The system provides personalized recommendations including breathing exercises, relaxation techniques, and an AI chatbot for real-time emotional support.',
    result: 'The platform enables proactive mental health screening at scale, helping institutions identify at-risk students early and deliver personalized wellness interventions without requiring in-person counseling for initial assessment.',
    features: [
      'ML-based stress, anxiety, and depression detection',
      'Personalized wellness recommendations',
      'AI chatbot for real-time emotional support',
      'Questionnaire-based mental health screening',
      'Admin dashboard for institutional oversight',
      'Secure student data handling',
    ],
    gallery: [
      '/portfolio/stress-mgmt.png',
      '/AI_Student_Stress_Management/screenshot-1.png',
      '/AI_Student_Stress_Management/screenshot-2.png',
      '/AI_Student_Stress_Management/screenshot-3.png',
      '/AI_Student_Stress_Management/screenshot-4.png',
    ],
  },
  {
    slug: 'lung-cancer-image-classifier',
    title: 'Lung Cancer Image Classifier',
    category: 'AI/ML',
    desc: 'CNN-based histopathology classifier that sorts lung tissue images into Adenocarcinoma, Benign, and Squamous Cell Carcinoma. Trained from scratch on a Kaggle dataset with augmentation and dropout, then wrapped in a Flask API with a clean upload-and-predict web interface for real-time inference on uploaded slides.',
    tech: ['Computer Vision', 'Python', 'TensorFlow', 'Keras', 'CNN', 'Flask', 'NumPy', 'Pillow'],
    color: '#ef4444',
    metric: '3-class histopathology detection',
    image: '/portfolio/lung-cancer.png',
    clientType: 'internal',
    year: 'Apr 2026',
    challenge: 'Histopathological analysis of lung tissue is critical for cancer diagnosis, but manual microscopy is slow and requires highly trained pathologists. Misclassification can delay treatment or lead to incorrect care plans.',
    solution: 'We trained a CNN from scratch on a Kaggle histopathology dataset with data augmentation and dropout for robust generalization. The model classifies lung tissue images into Adenocarcinoma, Benign, and Squamous Cell Carcinoma. It is served via a Flask API with a clean web interface for uploading slides and getting real-time predictions.',
    result: 'The classifier provides fast, accurate three-class histopathology detection, enabling pathologists to use AI as a second opinion for lung tissue analysis and reducing turnaround time for preliminary diagnoses.',
    features: [
      'Custom CNN architecture trained from scratch',
      'Three-class lung tissue classification',
      'Data augmentation for robust generalization',
      'Flask REST API for model serving',
      'Web interface for slide upload and prediction',
      'Real-time inference on uploaded images',
    ],
    gallery: [
      '/Lung_Cancer_Classification/thumbnail.png',
      '/Lung_Cancer_Classification/screenshot-1.png',
      '/Lung_Cancer_Classification/screenshot-2.png',
      '/Lung_Cancer_Classification/screenshot-3.png',
      '/Lung_Cancer_Classification/screenshot-4.png',
      '/Lung_Cancer_Classification/screenshot-5.png',
    ],
    video: '/Lung_Cancer_Classification/demo.mp4',
  },
  {
    slug: 'inventra-smart-inventory-management',
    title: 'Inventra: Smart Inventory Management',
    category: 'Web',
    desc: 'All-in-one platform for inventory tracking, order management, and real-time profitability analytics. Features advanced margin analytics with separated purchase and selling prices, streamlined order management, automated PDF billing with react-pdf, and deep inventory hierarchy for complex product catalogs.',
    tech: ['Next.js 16', 'React 19', 'TypeScript', 'Supabase', 'Tailwind CSS', 'Framer Motion', 'React-PDF'],
    color: '#0891b2',
    metric: 'Real-time margin analytics',
    image: '/portfolio/inventra.jpeg',
    objectPosition: 'left center',
    year: 'May 2026',
    challenge: 'Small and mid-sized businesses struggle with fragmented inventory systems that don\'t connect purchasing, selling, and profitability data. Manual spreadsheet tracking leads to stock mismatches and missed margin opportunities.',
    solution: 'We built Inventra, a unified platform that combines inventory tracking, order management, and real-time profitability analytics. It features separated purchase and selling prices for accurate margin calculation, automated PDF billing, and a deep inventory hierarchy for complex product catalogs.',
    result: 'Inventra gives business owners real-time visibility into margins and stock levels, replacing manual spreadsheets with an integrated system that automates billing and surfaces profitability insights across the entire product catalog.',
    features: [
      'Real-time margin analytics with separated purchase/selling prices',
      'Streamlined order management workflow',
      'Automated PDF invoice generation with React-PDF',
      'Deep inventory hierarchy for complex catalogs',
      'Supabase-powered real-time data sync',
      'Responsive dashboard with Framer Motion animations',
    ],
    gallery: [
      '/Inventra/thumbnail.jpg',
      '/Inventra/screenshot-1.jpg',
      '/Inventra/screenshot-2.jpg',
      '/Inventra/screenshot-3.jpg',
      '/Inventra/screenshot-4.jpg',
      '/Inventra/screenshot-5.jpg',
      '/Inventra/screenshot-6.jpg',
      '/Inventra/screenshot-7.jpg',
      '/Inventra/screenshot-8.jpg',
    ],
  },
  {
    slug: 'ai-voice-chat-agent',
    title: 'AI Voice Chat Agent',
    category: 'AI/ML',
    desc: 'Real-time voice conversation platform with 104+ AI characters using OpenAI GPT, TTS, and browser-based mic/speaker support. Features mood detection, session replay, WebRTC-based real-time API, interactive games, story adventures, and support for multiple providers including Claude, xAI, and local Ollama models. Deployable via Docker or Railway.',
    tech: ['Voice AI', 'LLM', 'FastAPI', 'WebSockets', 'OpenAI', 'WebRTC', 'Python', 'Docker', 'Railway', 'ElevenLabs'],
    color: '#0891b2',
    metric: '104+ AI characters',
    image: '/portfolio/ai-voice-agent.png',
    year: 'Nov 2025',
    challenge: 'Text-based AI chatbots lack the natural, engaging quality of voice conversations. Building a real-time voice platform that supports multiple AI providers and dozens of unique characters requires complex audio streaming, low-latency infrastructure, and robust session management.',
    solution: 'We built a real-time voice conversation platform using FastAPI, WebSockets, and WebRTC for low-latency audio streaming. The system supports 104+ AI characters powered by OpenAI GPT, TTS, and ElevenLabs, with mood detection, session replay, interactive games, and story adventures. It integrates multiple providers including Claude, xAI, and local Ollama models.',
    result: 'The platform delivers natural voice-based AI interactions with over 104 unique characters, supporting both entertainment and utility use cases with multi-provider flexibility and one-click deployment via Docker or Railway.',
    features: [
      '104+ AI characters with unique personalities',
      'Real-time voice streaming via WebRTC',
      'Mood detection and session replay',
      'Interactive games and story adventures',
      'Multi-provider support (OpenAI, Claude, xAI, Ollama)',
      'One-click deployment via Docker or Railway',
    ],
    gallery: [
      '/AI_Voice_Agent/thumbnail.png',
      '/AI_Voice_Agent/screenshot-1.png',
      '/AI_Voice_Agent/screenshot-2.png',
    ],
    video: ['/AI_Voice_Agent/Ai Voice Agent.mp4', '/AI_Voice_Agent/demo-realtime.mp4'],
  },
  {
    slug: 'safe-sawar-women-first-carpooling',
    title: 'Safe-Sawar: Women-First Carpooling',
    category: 'Mobile',
    desc: 'Pakistan\'s first NADRA-verified women-first carpooling platform built to tackle rising fuel costs. Features biometric identity verification, institution-based trust circles, live ride tracking, and an offline-capable Emergency SOS system via Bluetooth mesh networking. Male section added to enhance the wider userbase. Currently in beta.',
    tech: ['React Native', 'TypeScript', 'Firebase', 'Expo', 'Mesh Network', 'NADRA API', 'OpenStreetMap'],
    color: '#22c55e',
    metric: 'Beta, launching soon',
    image: '/portfolio/safe-sawar.png',
    clientType: 'internal',
    year: 'Mar 2026',
    challenge: 'Rising fuel costs and safety concerns make daily commuting difficult for women in Pakistan. Existing ride-sharing platforms don\'t provide identity verification or women-focused safety features, leaving a significant gap in safe, affordable transportation.',
    solution: 'We built Safe-Sawar, Pakistan\'s first NADRA-verified women-first carpooling platform. It features biometric identity verification, institution-based trust circles, live ride tracking, and an offline-capable Emergency SOS system using Bluetooth mesh networking. A male section was added to broaden the userbase while maintaining safety-first design.',
    result: 'Safe-Sawar is currently in beta, providing a verified, safety-first carpooling experience for women in Pakistan with innovative features like offline SOS and trust circles that don\'t exist in any competing platform.',
    features: [
      'NADRA biometric identity verification',
      'Institution-based trust circles',
      'Live ride tracking with OpenStreetMap',
      'Offline Emergency SOS via Bluetooth mesh networking',
      'Women-first with optional male section',
      'Firebase-powered real-time backend',
    ],
    gallery: [
      '/portfolio/safe-sawar.png',
      '/Safesawar/screenshot-1.png',
      '/Safesawar/screenshot-2.png',
      '/Safesawar/screenshot-3.jpeg',
      '/Safesawar/screenshot-4.jpeg',
      '/Safesawar/screenshot-5.jpeg',
      '/Safesawar/screenshot-6.jpeg',
      '/Safesawar/screenshot-7.jpeg',
      '/Safesawar/screenshot-8.jpeg',
      '/Safesawar/screenshot-9.jpeg',
      '/Safesawar/screenshot-10.jpeg',
      '/Safesawar/screenshot-11.jpeg',
    ],
  },
  {
    slug: 'decoding-of-life',
    title: 'Decoding of Life',
    category: 'AI/ML',
    desc: 'Delivered Decoding of Life for a client, deployed on Vercel. It combines the Gemini API with a RAG pipeline built on a Chinese source book to generate instant free previews and secure paid PDF reports in English and Chinese. Built with Next.js, Supabase, and Stripe.',
    tech: ['Next.js', 'Gemini API', 'RAG', 'Supabase', 'Stripe', 'TypeScript', 'PDF Generation'],
    color: '#8b5cf6',
    metric: 'Bilingual AI reports (EN and 中文)',
    image: '/Decoding Of Life Screenshots/Thumbnail.png',
    imageFit: 'contain',
    imageAspect: '1200 / 896',
    year: 'Jun 2026',
    clientType: 'upwork',
    challenge: 'The client needed an AI system that could turn a specialized Chinese source book into accurate, personalized numerology reports, delivered instantly, monetized securely, and readable by both English and Chinese speaking audiences.',
    solution: 'We built Decoding of Life with Next.js and deployed it on Vercel. A RAG pipeline grounds the Gemini API in the client\'s Chinese source book so every report stays faithful to the source material. Users get an instant free preview, then unlock full analysis and compatibility reports through Stripe, receiving polished bilingual PDFs by email. Supabase powers the data layer and an admin dashboard handles content, exports, and stats.',
    result: 'The platform delivers instant, grounded, bilingual reports with secure payments and automated delivery, giving the client a production-ready product that monetizes previews into paid PDF reports end to end.',
    features: [
      'Free preview, full analysis, and compatibility reports',
      'Bilingual output in English and Chinese',
      'Secure Stripe payments',
      'Automated email delivery with a responsive UI',
      'Admin dashboard with exports, stats, and content management',
    ],
    gallery: [
      '/Decoding Of Life Screenshots/Thumbnail.png',
      '/Decoding Of Life Screenshots/1.png',
      '/Decoding Of Life Screenshots/2.png',
      '/Decoding Of Life Screenshots/3.png',
      '/Decoding Of Life Screenshots/4.png',
      '/Decoding Of Life Screenshots/5.png',
      '/Decoding Of Life Screenshots/6.png',
      '/Decoding Of Life Screenshots/7.png',
      '/Decoding Of Life Screenshots/8.png',
      '/Decoding Of Life Screenshots/9.png',
      '/Decoding Of Life Screenshots/10.png',
    ],
    testimonial: {
      quote: 'Professional work by the team which fulfilled the job requirement. Good communication during the project and provide professional solution to tackle the issue arise from the project.',
      author: 'Vincent Yong',
      rating: 5,
      source: 'Upwork',
    },
  },
  {
    slug: 'cpai-bank-statement-analysis',
    title: 'CPAi: Bank Statement Analysis Dashboard',
    category: 'Web',
    desc: 'AI-powered credit profile analysis platform that auto-detects and parses PDF bank statements across 12 Malaysian bank formats. Features transaction categorization, balance checks, custom filtering rules, loan eligibility assessment, and exportable reports, all processed client-side for data privacy.',
    tech: ['Next.js', 'TypeScript', 'Python', 'AI/ML', 'PDF Parsing', 'Tailwind CSS'],
    color: '#22c55e',
    metric: '12 bank formats supported',
    image: '/Bank Statement Analysis Dashboard/thumbnail.png',
    year: 'May 2026',
    clientType: 'upwork',
    testimonial: {
      quote: 'Professional and reliable, excellent service.',
      author: 'Vincent Yong',
      rating: 5,
      source: 'Upwork',
    },
    challenge: 'Financial institutions manually review bank statements to assess creditworthiness, a tedious process that varies across dozens of bank formats. Errors in manual extraction lead to inaccurate loan decisions and compliance risks.',
    solution: 'We built CPAi, an AI-powered dashboard that auto-detects bank formats from uploaded PDF statements and extracts transaction data automatically. The platform categorizes transactions, checks balances, applies custom filtering rules, and calculates loan eligibility, all processed client-side to protect sensitive financial data.',
    result: 'CPAi reduces bank statement analysis from hours to seconds, supporting 12 Malaysian bank formats with automated extraction, intelligent categorization, and exportable credit reports that streamline the loan assessment pipeline.',
    features: [
      'Auto-detection of 12 Malaysian bank statement formats',
      'Client-side PDF parsing for data privacy',
      'Intelligent transaction categorization',
      'Balance verification and anomaly detection',
      'Custom transaction filtering rules',
      'Loan eligibility calculation and exportable reports',
    ],
    gallery: [
      '/Bank Statement Analysis Dashboard/thumbnail.png',
      '/Bank Statement Analysis Dashboard/screenshot-1.png',
      '/Bank Statement Analysis Dashboard/screenshot-2.png',
      '/Bank Statement Analysis Dashboard/screenshot-3.png',
      '/Bank Statement Analysis Dashboard/screenshot-4.png',
      '/Bank Statement Analysis Dashboard/screenshot-5.png',
      '/Bank Statement Analysis Dashboard/screenshot-6.png',
      '/Bank Statement Analysis Dashboard/screenshot-7.png',
      '/Bank Statement Analysis Dashboard/screenshot-8.png',
      '/Bank Statement Analysis Dashboard/screenshot-9.png',
      '/Bank Statement Analysis Dashboard/screenshot-10.png',
      '/Bank Statement Analysis Dashboard/screenshot-11.png',
    ],
    video: '/Bank Statement Analysis Dashboard/Demo.mp4',
  },
  {
    slug: 'persona-track-ai',
    title: 'Persona Track A.I',
    category: 'AI/ML',
    desc: 'A real-time computer vision pipeline that detects people and classifies perceived gender in live video streams or images. Combines a YOLOv8 person detector with a TorchScript gender classifier and overlays labels directly on the video feed. Designed for fast inference and flexible inputs including webcam, video file, or single image, demonstrating an end-to-end vision workflow from detection and safe cropping to classification and visualization.',
    tech: ['Computer Vision', 'YOLOv8', 'Python', 'TorchScript', 'OpenCV', 'CUDA', 'Deep Learning'],
    color: '#8b5cf6',
    metric: 'Real-time gender classification',
    image: '/Persona_AI/thumbnail.png',
    year: '2026',
    challenge: 'Real-time person attribute classification from video feeds requires fast, accurate detection combined with a lightweight classifier that runs without lag on live streams.',
    solution: 'We built a pipeline using YOLOv8 for person detection and a TorchScript gender classifier for portable, fast inference. The system overlays bounding boxes and labels directly on frames with support for frame skipping and optional FP16 inference on CUDA for maximum throughput.',
    result: 'Delivers real-time person detection and gender classification across webcam, video files, and static images with robust preprocessing including safe cropping, resizing, and normalization.',
    features: [
      'Real-time person detection using YOLOv8 with configurable confidence and input size',
      'Gender classification via a TorchScript model for fast, portable inference',
      'Works with webcam, video files, and single images',
      'Visual overlays with bounding boxes and labels rendered directly on frames',
      'Performance options: frame skipping and optional FP16 inference on CUDA',
      'Robust preprocessing with resizing, normalization, and safe cropping',
    ],
    gallery: [
      '/Persona_AI/thumbnail.png',
      '/Persona_AI/screenshot-1.png',
    ],
  },
  {
    slug: 'propex-real-estate-platform',
    title: 'Propex: Real Estate Platform',
    category: 'Web',
    desc: 'A full-stack real estate web platform for property discovery and content management. The React UI features a hero carousel, curated listings with filters, and detailed property pages. An admin dashboard manages listings, featured selections, and hero slides with drag-and-drop image uploads. Backed by a Node/Express REST API with PostgreSQL, plus an optional Flask ML service for AI-driven price prediction and market trend insights.',
    tech: ['React', 'React Router', 'Framer Motion', 'Node.js', 'Express', 'PostgreSQL', 'Multer', 'Flask', 'scikit-learn'],
    color: '#22c55e',
    metric: 'AI-powered price prediction',
    image: '/Propex/thumbnail.png',
    year: '2026',
    challenge: 'Pakistan\'s real estate market lacks a modern, data-driven platform that combines intuitive property browsing with accurate AI-powered valuations and easy content management for agents.',
    solution: 'We built Propex, a full-stack platform with a polished React frontend for property discovery, a Node/Express REST API with PostgreSQL for listings and analytics, and an optional Flask ML service for price prediction and market trends using scikit-learn.',
    result: 'Propex delivers a seamless property browsing experience with curated listings, AI price predictions, and a powerful admin dashboard that gives agents full control over listings, featured properties, and hero content.',
    features: [
      'Public site with curated listings, filters, and property detail views',
      'Admin dashboard for managing listings, hero slides, and featured properties',
      'Drag-and-drop and URL-based image uploads served from the backend',
      'REST API with analytics endpoints and listing settings',
      'Optional ML service for AI price prediction and market trend insights',
      'Responsive UI with Framer Motion animations',
    ],
    gallery: [
      '/Propex/thumbnail.png',
      '/Propex/2.png',
      '/Propex/3.png',
      '/Propex/4.png',
      '/Propex/5.png',
      '/Propex/6.png',
      '/Propex/7.png',
      '/Propex/8.png',
    ],
  },
  {
    slug: 'politian-voting-platform',
    title: 'Politian: Transparent Voting Platform',
    category: 'Web',
    desc: 'A secure and transparent online voting platform for Pakistani elections. Features voter registration, campaign browsing, real-time vote tallying, and an admin panel for managing candidates and elections. Built with end-to-end security and simple registration to maximize voter participation.',
    tech: ['React', 'Node.js', 'MongoDB', 'Express', 'JWT', 'Tailwind CSS'],
    color: '#f59e0b',
    metric: 'Secure online voting',
    image: '/Politian/screenshot-1.png',
    clientType: 'internal',
    year: 'Apr 2026',
    challenge: 'Traditional voting processes in Pakistan face accessibility barriers, long queues, and transparency concerns. Many eligible voters, especially overseas Pakistanis, cannot participate in elections due to logistical constraints.',
    solution: 'We built Politian, a secure online voting platform that allows registered voters to browse election campaigns, cast votes, and view real-time results. The platform features JWT-based authentication, admin controls for managing candidates and elections, and a clean interface designed for maximum accessibility.',
    result: 'Politian demonstrates a viable model for transparent digital elections, providing secure voter registration, real-time tallying, and admin oversight in a platform that could extend voting access to millions of disenfranchised citizens.',
    features: [
      'Secure voter registration and authentication',
      'Election campaign browsing with candidate profiles',
      'Real-time vote tallying and result visualization',
      'Admin panel for election and candidate management',
      'JWT-based security with role-based access',
      'Mobile-responsive interface for maximum reach',
    ],
    gallery: [
      '/Politian/screenshot-1.png',
      '/Politian/screenshot-2.png',
      '/Politian/screenshot-3.png',
      '/Politian/screenshot-4.png',
      '/Politian/screenshot-5.png',
    ],
  },
];
